// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tasks struct {
	ID     int64       `json:"id"`
	Name   string      `json:"name"`
	Status bool        `json:"status"`
	UserID pgtype.Int8 `json:"user_id"`
}

type Users struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
