name: Go Lint and Format

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache:  true

    - name: Run go fmt
      run: |
        go fmt ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        working-directory: ./backend
        args: ./... --timeout=10m